config/routes.rb
Rails.application.routes.draw do

  root to: 'cocktails#index'

  resources :cocktails, except: :destroy do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, allow_blank: false,uniqueness: true
  has_many :doses,  dependent: :destroy
  has_many :ingredients, through: :doses

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true, allow_blank: false
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def show
    @dose = Dose.new
  end

  def edit
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path
    else
      render 'edit'
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: :create

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/cocktails/_form.html.erb
<!-- cocktails form -->

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
< <%= render 'form' %>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">

    <% @cocktails.each do |cocktail| %>

      <div class="col-xs-12 col-sm-6 col-lg-4">
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card card-link" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( '<%= cl_image_path(cocktail.photo? ? cocktail.photo : 'fysedljjycu4kwcqsasb') %>' );">

              <h1><%= cocktail.name %></h1>

          </div>
        <% end %>
      </div>

    <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
 <%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( <%= @cocktail.photo %> );">
    <h1><%= @cocktail.name %></h1>
</div>

<div class="container">
  <div class="wrapper">

    <div class="card-show">
      <h3>Description</h3>
      <h4><%= @cocktail.description %></h4>

      <%= link_to "Edit the description", edit_cocktail_path(@cocktail), class: "btn btn-info" %>

    </div>

    <div class="card-show">
      <h3>Ingredients</h3>
      <% @cocktail.doses.each do |dose| %>
        <ul class="list-unstyled">
          <li>
          <strong><%= dose.ingredient.name %></strong>
            <%= dose.description %>

            <%= link_to(dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }) do %>
              <i class="fa fa-trash-o" aria-hidden="true"></i>
            <% end %>

          </li>
        </ul>
      <% end %>

       <%= simple_form_for [@cocktail, @dose] do |f| %>
         <%= f.input :description %>
         <%= f.input :ingredient_id, collection: Ingredient.all %>
         <%= f.button :submit, class: "btn btn-info" %>
       <% end %>
    </div>

  </div>
</div>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
 <%= render 'form' %>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <%= link_to(cocktails_path, class: "navbar-wagon-link") do %>
    <%= image_tag "icon.png", class: "avatar"%>
  <% end %>

  <%= link_to(new_cocktail_path, class: "navbar-wagon-link") do %>
    <i class="fa fa-plus fa-3x" aria-hidden="true" style="color:white"></i>
  <% end %>

</div>